### ISSUE TITLE
i don't konw if i am wrong

### ISSUE THREAD

**Issue by luqingxuan** [internetErik/gulp-htmlincluder#2]
i have a html file (index.html) like this:
&lt;!DOCTYPE html>
&lt;html>
&lt;head>
&lt;!--#insert file="../commonMeta.html" -->
&lt;!--#insert file="../commonCss.html" -->
&lt;/head>
&lt;body>
    
&lt;/body>
&lt;/html>
u see,include three sub files,but they are not in the same folder with index.html,
when process html by this plugin,this is a bug : file not exist, can u help me ?

**Comment by tashbenbetov** [comment]
I have same problem.

**Comment by internetErik** [comment]
Sorry I missed the initial issue here. I haven't looked at this repo in a minute.

Try naming the files that you want to include with a `-` in front of them. So, rename `commonMeta.html` to `-commonMeta.html`.

**Comment by whisper12** [comment]
I have same problem....

**Comment by internetErik** [comment]
The naming of the files does matter. Inserted files need to have a leading '-' while files used for wrapping other files start with a '_'. Does that help?
