### ISSUE TITLE
execute only once, if return the stream

### ISSUE THREAD

**Issue by bi-kai** [internetErik/gulp-htmlincluder#3]
execute only once, if return the stream:

```
return gulp.src(...)
          .pipe(htmlincluder())
```

without `return`, it's ok. is it a mistake?

**Comment by internetErik** [comment]
I can't reproduce this. A watch still seems to capture changes and run the includer again properly.  Could you provide a simple repo that reproduces the problem or the gulpfile you're using?

**Comment by bi-kai** [comment]
@internetErik gulpfile like this will trigger include action only once:

```
//run `gulp watch` in cli
gulp.task("watch", function () {
    gulp.watch("src/html/**/*", ["html"]);
});

gulp.task("html", function () {
    return gulp.src(["src/html/**/*.html"])
        .pipe(htmlincluder())
        .pipe(gulp.dest("./dist"));
});
```

remove the `return`, will trigger include action correctly while saving the html file.

**Comment by bi-kai** [comment]
@internetErik any ideas now?

**Comment by bi-kai** [comment]
I'm using template engine now, like swig/ejs/pug, I select nunjucks at last.

**Comment by bi-kai** [comment]
closed without fix the problem.
